# Generated by Django 4.2.30 on 2026-07-04 13:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Клиентский идентификатор')),
                ('observed_at', models.DateTimeField(verbose_name='Дата и время замера')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(-60), django.core.validators.MaxValueValidator(60)], verbose_name='Температура, °C')),
                ('pressure', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(600), django.core.validators.MaxValueValidator(1100)], verbose_name='Давление, гПа')),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скорость ветра, м/с')),
                ('wind_direction', models.CharField(blank=True, choices=[('N', 'N'), ('NNE', 'NNE'), ('NE', 'NE'), ('ENE', 'ENE'), ('E', 'E'), ('ESE', 'ESE'), ('SE', 'SE'), ('SSE', 'SSE'), ('S', 'S'), ('SSW', 'SSW'), ('SW', 'SW'), ('WSW', 'WSW'), ('W', 'W'), ('WNW', 'WNW'), ('NW', 'NW'), ('NNW', 'NNW')], max_length=3, verbose_name='Направление ветра (румб)')),
                ('precipitation_amount', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Кол-во осадков, мм')),
                ('cloudiness', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Облачность, %')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Подтверждено'), ('rework', 'Доработка'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='Аномалия')),
                ('resubmit_count', models.PositiveSmallIntegerField(default=0, verbose_name='Повторных отправок')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Доп. атрибуты')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архив')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Наблюдение',
                'verbose_name_plural': 'Наблюдения',
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='Phenomenon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Погодное явление',
                'verbose_name_plural': 'Справочник: погодные явления',
            },
        ),
        migrations.CreateModel(
            name='PrecipitationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип осадков',
                'verbose_name_plural': 'Справочник: типы осадков',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/', verbose_name='Изображение')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='observations.observation', verbose_name='Наблюдение')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='phenomena',
            field=models.ManyToManyField(blank=True, to='observations.phenomenon', verbose_name='Явления'),
        ),
        migrations.AddField(
            model_name='observation',
            name='precipitation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.precipitationtype', verbose_name='Тип осадков'),
        ),
        migrations.AddField(
            model_name='observation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='stations.station', verbose_name='Точка'),
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32, verbose_name='Действие')),
                ('old_status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Подтверждено'), ('rework', 'Доработка'), ('rejected', 'Отклонено')], max_length=10, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Подтверждено'), ('rework', 'Доработка'), ('rejected', 'Отклонено')], max_length=10, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_log', to='observations.observation', verbose_name='Наблюдение')),
            ],
            options={
                'verbose_name': 'Запись журнала модерации',
                'verbose_name_plural': 'Журнал модерации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['status', 'observed_at'], name='observation_status_76d6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['station'], name='observation_station_5774d0_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['author'], name='observation_author__eb03de_idx'),
        ),
    ]
