# Generated by Django 4.2.30 on 2026-07-16 12:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0002_alter_station_options_alter_station_created_at_and_more'),
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'запись журнала модерации', 'verbose_name_plural': 'журнал модерации'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-observed_at'], 'verbose_name': 'наблюдение', 'verbose_name_plural': 'наблюдения'},
        ),
        migrations.AlterModelOptions(
            name='phenomenon',
            options={'verbose_name': 'погодное явление', 'verbose_name_plural': 'справочник: погодные явления'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'фото', 'verbose_name_plural': 'фото'},
        ),
        migrations.AlterModelOptions(
            name='precipitationtype',
            options={'verbose_name': 'тип осадков', 'verbose_name_plural': 'справочник: типы осадков'},
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(max_length=32, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='модератор'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Подтверждено'), ('rework', 'Доработка'), ('rejected', 'Отклонено')], max_length=10, verbose_name='новый статус'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_log', to='observations.observation', verbose_name='наблюдение'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='old_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Подтверждено'), ('rework', 'Доработка'), ('rejected', 'Отклонено')], max_length=10, verbose_name='старый статус'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='client_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='клиентский идентификатор'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cloudiness',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='облачность, %'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='доп. атрибуты'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='is_anomaly',
            field=models.BooleanField(default=False, verbose_name='аномалия'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='архив'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата модерации'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated', to=settings.AUTH_USER_MODEL, verbose_name='модератор'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observed_at',
            field=models.DateTimeField(verbose_name='дата и время замера'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='phenomena',
            field=models.ManyToManyField(blank=True, to='observations.phenomenon', verbose_name='явления'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='precipitation_amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='кол-во осадков, мм'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='precipitation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.precipitationtype', verbose_name='тип осадков'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='pressure',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(600), django.core.validators.MaxValueValidator(1100)], verbose_name='давление, гПа'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='resubmit_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='повторных отправок'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='stations.station', verbose_name='точка'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Подтверждено'), ('rework', 'Доработка'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(-60), django.core.validators.MaxValueValidator(60)], verbose_name='температура, °C'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='версия'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('NNE', 'NNE'), ('NE', 'NE'), ('ENE', 'ENE'), ('E', 'E'), ('ESE', 'ESE'), ('SE', 'SE'), ('SSE', 'SSE'), ('S', 'S'), ('SSW', 'SSW'), ('SW', 'SW'), ('WSW', 'WSW'), ('W', 'W'), ('WNW', 'WNW'), ('NW', 'NW'), ('NNW', 'NNW')], max_length=3, verbose_name='направление ветра (румб)'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='wind_speed',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='скорость ветра, м/с'),
        ),
        migrations.AlterField(
            model_name='phenomenon',
            name='code',
            field=models.SlugField(max_length=32, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='phenomenon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='phenomenon',
            name='name',
            field=models.CharField(max_length=64, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='observations.observation', verbose_name='наблюдение'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='размер, байт'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки'),
        ),
        migrations.AlterField(
            model_name='precipitationtype',
            name='code',
            field=models.SlugField(max_length=32, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='precipitationtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='precipitationtype',
            name='name',
            field=models.CharField(max_length=64, verbose_name='наименование'),
        ),
    ]
