# Generated by Django 4.2.30 on 2026-07-16 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_alter_moderationlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='water_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='заполняется для точек на побережье и островах', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(35)], verbose_name='температура воды, °C'),
        ),
    ]
