# Generated by Django 4.2.30 on 2026-07-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_observation_water_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('N', 'С'), ('NNE', 'ССВ'), ('NE', 'СВ'), ('ENE', 'ВСВ'), ('E', 'В'), ('ESE', 'ВЮВ'), ('SE', 'ЮВ'), ('SSE', 'ЮЮВ'), ('S', 'Ю'), ('SSW', 'ЮЮЗ'), ('SW', 'ЮЗ'), ('WSW', 'ЗЮЗ'), ('W', 'З'), ('WNW', 'ЗСЗ'), ('NW', 'СЗ'), ('NNW', 'ССЗ')], max_length=3, verbose_name='направление ветра (румб)'),
        ),
    ]
