# Generated by Django 4.2.30 on 2026-07-21 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_observation_wind_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=64, verbose_name='наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'аллерген',
                'verbose_name_plural': 'справочник: аллергены',
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='obs_type',
            field=models.CharField(choices=[('full', 'Полное наблюдение'), ('express', 'Экспресс-замер'), ('allergy', 'Аллергонаблюдение')], default='full', max_length=10, verbose_name='тип наблюдения'),
        ),
        migrations.AddField(
            model_name='observation',
            name='pollen_level',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('very_high', 'Очень высокий')], max_length=10, verbose_name='уровень пыльцы'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cloudiness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='облачность, %'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='precipitation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='observations.precipitationtype', verbose_name='тип осадков'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(600), django.core.validators.MaxValueValidator(1100)], verbose_name='давление, гПа'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='wind_speed',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='скорость ветра, м/с'),
        ),
        migrations.AddField(
            model_name='observation',
            name='allergen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='observations.allergen', verbose_name='аллерген'),
        ),
    ]
