# Generated by Django 4.2.30 on 2026-07-21 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_allergen_observation_obs_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(-60), django.core.validators.MaxValueValidator(60)], verbose_name='температура, °C'),
        ),
    ]
