# Generated by Django 4.2.30 on 2026-07-16 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'запись журнала действий', 'verbose_name_plural': 'журнал действий'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'уведомление', 'verbose_name_plural': 'уведомления'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=64, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_value',
            field=models.TextField(blank=True, verbose_name='новое значение'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='obj',
            field=models.CharField(blank=True, max_length=255, verbose_name='объект'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_value',
            field=models.TextField(blank=True, verbose_name='старое значение'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='причина'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('status', 'Смена статуса наблюдения'), ('report', 'Готовность отчёта'), ('moderation', 'Назначение модерации'), ('other', 'Прочее')], default='other', max_length=16, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='получатель'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=500, verbose_name='текст'),
        ),
    ]
