# Generated by Django 4.2.30 on 2026-07-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='block_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='причина блокировки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата согласия на обработку ПД'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='заблокирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='удалён (анонимизирован)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последняя активность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('observer', 'Наблюдатель'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='observer', max_length=16, verbose_name='роль'),
        ),
    ]
