# Generated by Django 4.2.30 on 2026-07-04 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Высота над уровнем моря, м')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('equipment', models.TextField(blank=True, verbose_name='Оборудование')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичная')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Точка наблюдения',
                'verbose_name_plural': 'Точки наблюдения',
                'indexes': [models.Index(fields=['is_public', 'is_active'], name='stations_st_is_publ_5804c0_idx')],
            },
        ),
    ]
