# Generated by Django 4.2.30 on 2026-07-16 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'точка наблюдения', 'verbose_name_plural': 'точки наблюдения'},
        ),
        migrations.AlterField(
            model_name='station',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='station',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='оборудование'),
        ),
        migrations.AlterField(
            model_name='station',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='высота над уровнем моря, м'),
        ),
        migrations.AlterField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
        migrations.AlterField(
            model_name='station',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='публичная'),
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=120, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='station',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='station',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
