# Generated by Django 4.2.30 on 2026-07-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_station_options_alter_station_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='location_type',
            field=models.CharField(choices=[('inland', 'Материковая'), ('coast', 'Побережье'), ('island', 'Остров')], default='inland', help_text='для побережья и островов доступна температура воды; для островов скорость ветра дублируется в узлах', max_length=10, verbose_name='тип местности'),
        ),
    ]
