# Generated by Django 4.2.30 on 2026-07-04 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Период с')),
                ('date_to', models.DateField(verbose_name='Период по')),
                ('fmt', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], default='csv', max_length=4, verbose_name='Формат')),
                ('state', models.CharField(choices=[('pending', 'Формируется'), ('ready', 'Готов'), ('empty', 'Нет данных'), ('error', 'Ошибка')], default='pending', max_length=8, verbose_name='Состояние')),
                ('file', models.FileField(blank=True, upload_to='reports/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', verbose_name='Точка (пусто — весь регион)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
    ]
