# Generated by Django 4.2.30 on 2026-07-16 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0002_alter_station_options_alter_station_created_at_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'отчёт', 'verbose_name_plural': 'отчёты'},
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_from',
            field=models.DateField(verbose_name='период с'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_to',
            field=models.DateField(verbose_name='период по'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, upload_to='reports/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fmt',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], default='csv', max_length=4, verbose_name='формат'),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.CharField(choices=[('pending', 'Формируется'), ('ready', 'Готов'), ('empty', 'Нет данных'), ('error', 'Ошибка')], default='pending', max_length=8, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='report',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', verbose_name='точка (пусто — весь регион)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
